import { fSub } from 'src/utils/format-time';

import { CONFIG } from 'src/config-global';

import {
  _id,
  _ages,
  _roles,
  _prices,
  _emails,
  _ratings, 
  _nativeS,
  _nativeM,
  _nativeL,
  _domains,
  _percents,
  _booleans,
  _pocNames,
  _addresses,
  _sentences,
  _lastNames,
  _fullNames,
  _tourNames,
  _jobTitles,
  _taskNames,
  _fileNames,
  _postTitles,
  _firstNames,
  _eventNames,
  _courseNames,
  _fullAddress,
  _pocContacts,
  _companyNames,
  _productNames,
  _descriptions,
  _phoneNumbers,
  _countryNames,
  _walletBalance,
  _paymentMethod,
  _remarks,
  _mealItem,
  _location,
  _locationEmail,
  _cutOffTime,
  _createdAt,
  _updatedAt,
  _mealTime,
} from './assets';

// ----------------------------------------------------------------------

const { assetURL } = CONFIG.site;

export const _mock = {
  id: (index) => _id[index],
  time: (index) => fSub({ days: index, hours: index }),
  boolean: (index) => _booleans[index],
  role: (index) => _roles[index],
  // Text
  courseNames: (index) => _courseNames[index],
  fileNames: (index) => _fileNames[index],
  eventNames: (index) => _eventNames[index],
  taskNames: (index) => _taskNames[index],
  postTitle: (index) => _postTitles[index],
  jobTitle: (index) => _jobTitles[index],
  tourName: (index) => _tourNames[index],
  productName: (index) => _productNames[index],
  sentence: (index) => _sentences[index],
  description: (index) => _descriptions[index],
  paymentMethod: (index) => _paymentMethod[index],
  location: (index) => _location[index],
  locationEmail: (index) => _locationEmail[index],
  cutOffTime: (index) => _cutOffTime[index],
  createdAt: (index) => _createdAt[index],
  updatedAt: (index) => _updatedAt[index],
  
  // Contact
  email: (index) => _emails[index],
  address : (index) => _addresses[index],
  domain : (index) => _domains[index],
  phoneNumber: (index) => _phoneNumbers[index],
  fullAddress: (index) => _fullAddress[index],
  // Name
  pocName: (index) => _pocNames[index],
  pocContacts: (index) => _pocContacts[index],
  firstName: (index) => _firstNames[index],
  lastName: (index) => _lastNames[index],
  fullName: (index) => _fullNames[index],
  companyNames: (index) => _companyNames[index],
  countryNames: (index) => _countryNames[index],
  // Number
  number: {
    percent: (index) => _percents[index],
    rating: (index) => _ratings[index],
    age: (index) => _ages[index],
    walletBalance: (index) => _walletBalance[index],
    price: (index) => _prices[index],
    nativeS: (index) => _nativeS[index],
    nativeM: (index) => _nativeM[index],
    nativeL: (index) => _nativeL[index],
  },
  // Review
  remarks : (index) => _remarks[index],
  ratings : (index) => _ratings[index],
  mealItem : (index) => _mealItem[index],
  mealTime : (index) => _mealTime[index],
  // Image
  image: {
    cover: (index) => `${assetURL}/assets/images/cover/cover-${index + 1}.webp`,
    avatar: (index) => `${assetURL}/assets/images/avatar/avatar-${index + 1}.webp`,
    travel: (index) => `${assetURL}/assets/images/travel/travel-${index + 1}.webp`,
    course: (index) => `${assetURL}/assets/images/course/course-${index + 1}.webp`,
    company: (index) => `${assetURL}/assets/images/company/company-${index + 1}.webp`,
    product: (index) => `${assetURL}/assets/images/m-product/product-${index + 1}.webp`,
    portrait: (index) => `${assetURL}/assets/images/portrait/portrait-${index + 1}.webp`,
  },
};
